### ISSUE TITLE
Report reveals student identities when blind marking is enabled

### ISSUE THREAD

**Issue by jonlucholmes** [pauln/moodle-report_componentgrades#11]
Running the report to export marking guide or rubric component grades will reveal the identities of students when blind marking is enabled. This is an issue as the identities of students aren't revealed in a Moodle assignment until the grades are sent to the gradebook.

**Comment by marcusgreen** [comment]
Thanks for that, I will add that to the documentation. There is another issue that needs adding and that is that it does not work correctly if an assignment is set up for multiple submissions.

**Comment by aspark21** [comment]
@marcusgreen Is this a big job to implement both of these?

Can speak to Seb about funding this.

**Comment by marcusgreen** [comment]
I investigated the multiple submissions issue a few months ago and I can imagine how it could be solved but gave up as too big a job on my own time. I have worked extensively with anonymous marking for other plugins recently so I understand the issues, but I have never thought about it in relation to this plugin.  Contact me directly by the usual methods. if you would like to discuss further.

**Comment by aspark21** [comment]
Hi Marcus, do you have any news on this one?
It's been lingering for a while. Can follow up with Mike, I gather he was away so might not have been able to follow through on this.

**Comment by marcusgreen** [comment]
Yes, I have news. I have code for respecting blind marking in this branch.
https://github.com/marcusgreen/moodle-report_componentgrades/tree/blind_mark
Could you install it and confirm it works as you expect, then I can merge it into the main branch.
My apologies, I should have got back to you on this one.

**Comment by aspark21** [comment]
Will try to get it tested this week 😄

**Comment by aspark21** [comment]
Sorry didn't reply to this bu yes we tested and seemed to pass our sanity checks

**Comment by marcusgreen** [comment]
Thanks, I will take another look at it myself as I have forgotten the details and see if I can get it merged.

**Comment by marcusgreen** [comment]
This feature is nows incorporated in version 1.3 which is in master/cgrades_1.3 and in the plugins database
https://moodle.org/plugins/report_componentgrades
