### ISSUE TITLE
include users groups in export.

### ISSUE THREAD

**Issue by danmarsden** [pauln/moodle-report_componentgrades#14]
It would be good if the users groups could be included in the export - PR incoming.

**Comment by marcusgreen** [comment]
I think you are missing adding the $groups variable to the end of the function call in guide.php to the line that reads
report_componentgrades_add_data($sheet, $students, $gradinginfopos, 'guide');
And it should read
report_componentgrades_add_data($sheet, $students, $gradinginfopos, 'guide', $groups);

(almost at the end of the file)
