### ISSUE TITLE
Support for Ranged Rubrics

### ISSUE THREAD

**Issue by dmitriim** [pauln/moodle-report_componentgrades#24]
Recently we have developed a new Ranged rubrics plugin see https://github.com/catalyst/moodle-gradingform_rubric_ranges 

Would be nice to get a support for this one as well.

**Comment by marcusgreen** [comment]
I think I have looked at that plugin (I work for Catalyst). Component grades has been retired to be replaced by https://github.com/marcusgreen/moodle-report_advancedgrading

And it is quite easy to add support for additional advanced grading methods. I did it recently for one similar to rubric_ranges, it allows a mark within a range.

I need to mark component grades up as retired and no longer supported.

**Comment by dmitriim** [comment]
Thanks for heads up @marcusgreen  ! 

Would be nice to add a note here as well https://moodle.org/plugins/report_componentgrades

I have created https://github.com/marcusgreen/moodle-report_advancedgrading/issues/16 We will check if the client is interested in a new plugin and hopfully wil be able to work on that feature shortly.
